# Generated by Django 3.1 on 2020-10-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_auto_20201031_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field='height_field', upload_to='post/%Y/%m', width_field='width_field'),
        ),
    ]
