# Generated by Django 3.1 on 2020-10-31 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20201031_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
