# Generated by Django 3.1 on 2020-08-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20200826_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
    ]
