# Generated by Django 3.1 on 2020-10-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
