# Generated by Django 3.1 on 2020-10-31 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
