# Generated by Django 3.1 on 2020-10-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_like_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='like',
        ),
    ]
