# Generated by Django 3.1 on 2020-10-20 15:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0010_auto_20201020_1701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('like', 'post')},
        ),
    ]
