# Generated by Django 3.1 on 2020-10-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0014_auto_20201024_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='c_post',
            new_name='post',
        ),
    ]
