# Generated by Django 3.1 on 2020-08-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0016_auto_20200827_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default=1, max_length=120),
        ),
    ]
