# Generated by Django 3.1 on 2020-10-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0017_auto_20201024_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='c_post',
        ),
    ]
