# Generated by Django 3.1 on 2020-08-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0028_auto_20200827_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=120),
        ),
    ]
