# Generated by Django 3.1 on 2020-09-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0030_auto_20200829_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
