# Generated by Django 3.1 on 2020-10-10 08:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Login', '0002_auto_20201010_1022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollower',
            unique_together={('follower', 'follower')},
        ),
    ]
