# Generated by Django 3.1 on 2020-10-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20201010_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollower',
            name='is_follower',
            field=models.BooleanField(default=False),
        ),
    ]
