# Generated by Django 3.1 on 2020-10-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_userfollower_is_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollower',
            name='is_follower',
        ),
    ]
