# Generated by Django 3.1 on 2020-10-11 08:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Login', '0005_remove_userfollower_is_follower'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollows',
            unique_together={('following', 'following')},
        ),
    ]
