# Generated by Django 3.1 on 2020-10-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_auto_20201011_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
